# -*- coding: utf-8 -*-
"""Proyecto_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/moreyg/Tiker-Monster/blob/main/Start_files/Proyecto_v1.ipynb

<img src="https://raw.githubusercontent.com/ITBA-Python/Certificacion-Profesional-Python/main/assets/clase2/Headers%20c%C3%A1talogo_Mesa%20de%20trabajo%201%20copia%2044.jpg" width="800">



# Certificación profesional de Python

# Clase 7

El objetivo de la clase es seguir sumando experiencia de trabajo con programación aprendiendo los siguientes temas.

*   APIs y formato JSON
*   Programación Orientada a Objetos

La clase incluye teoría y práctica sobre cada tema aprendido.

<img src="https://raw.githubusercontent.com/ITBA-Python/Certificacion-Profesional-Python/main/assets/clase2/LOGOTIPO_sin_fondo_positivo_sin_bajada.png" width="400">

# APIs y formato JSON

Comenzaremos viendo qué es una API, cómo se aplican en el ámbito de los servicios web y cómo se estructuran los datos que intercambiamos, igual que vimos en clases anteriores con XML.

## APIs web - APIs REST

Una API es una interfaz de programación de aplicaciones. Es la forma que tiene un componente de software de exponer una interfaz (en la forma de un conjunto de funciones, subrutinas, procedimientos o protocolos) para ser utilizado por otro componente de software y que puedan conectarse y comunicarse. En otras palabras, una API permite interactuar con una computadora o sistema para obtener datos o ejecutar operaciones.

Esta arquitectura sigue también el modelo de cliente-servidor. La aplicación o servicio que realiza el acceso o solicitud de datos es el cliente, mientras que la computadora o servicio que posee los datos o recursos es el servidor.

### RESTful

Por otro lado, REST es simplemente un conjunto de límites de arquitectura, un estilo de como implementar la arquitectura de la comunicación entre aplicaciones denominado transferencia de estado representacional, no es un protocolo ni un estándar. Una API REST o RESTful API es una API que está implementada siguiendo los principios de diseño de REST.

La transferencia de datos se realiza mediante una representación del recurso, y se efectúa mediante el protocolo HTTP que estudiamos en clases anteriores.

Algunos de los criterios de desarrollo más importantes para hacer una API REST son:

 - Arquitectura ciente-servidor a trvéz de HTTP.

 - Comunicación <b>sin estado</b>. Esto implica que entre cada request el servidor no almacena ningún dato, y por lo tanto todos los requests son independientes.

 - Una interfaz uniforme entre todos los recursos, que permite estandarizar los request.

 - Los recursos se manejan mediante URIs (similares a las URLs pero más genéricas). Cuando hablamos de API suele utilizarse el término <b>endpoint</b> para referirse a los puntos de contacto con los datos, la dirección mediante la cual el cliente puede interactuar con un recurso del servidor típicamente mediante una URI.

 - Se utilizan los mismos verbos que usa el protocolo HTTP:
   - GET: permite obtener los datos de un recurso
   - POST: permite crear un nuevo recurso}
   - PUT: permite modificar un recurso existente
   - DELETE: permite eliminar un recurso


 - Las transferencias de datos se suelen realizar en formato JSON, de forma similiar a como los servicios web que vimos en clases anteriores usan el formato XML.

## Formato JSON

Si bien XML cumplía su labor, podemos darnos cuenta que tiene mucho texto duplicado debido a las etiquetas. Por eso se desarrolló un formato nuevo para lograr una transferencia de datos estructurados más eficiente, utilizando otro formato de texto que resulte más liviano.

El formato JSON (Javascript Object Notation) es simplemente una representación que sigue la forma que tiene el lenguaje Javascript para estructurar datos en objetos. Se puede pensar como un diccionario de Python, con una sintaxis muy similar que utiliza pares clave-valor para representar los datos. Si bien su origen proviende de Javascript, su amplio uso en las APIs hizo que se considere un formato independiente y que pueda trabajarse en cualquier lenguaje de programación, lo cual a su vez facilita el desarrollo de APIs.

Veamos ejemplos para entender porque es más eficiente y liviano que XML.

Ejemplo de archivo XML:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Edit_Mensaje SYSTEM "Edit_Mensaje.dtd">

<Edit_Mensaje>
     <Mensaje>
          <Remitente>
               <Nombre>Nombre del remitente</Nombre>
               <Mail> Correo del remitente </Mail>
          </Remitente>
          <Destinatario>
               <Nombre>Nombre del destinatario</Nombre>
               <Mail>Correo del destinatario</Mail>
          </Destinatario>
          <Texto>
               <Asunto>
                    Este es mi documento con una estructura muy sencilla
                    no contiene atributos ni entidades...
               </Asunto>
               <Parrafo>
                    Este es mi documento con una estructura muy sencilla
                    no contiene atributos ni entidades...
               </Parrafo>
          </Texto>
     </Mensaje>
</Edit_Mensaje>
```

Ejemplo con la misma información, pero ahora en formato JSON:
```json
{
    "edit_mensaje": {
        "mensaje": {
            "remitente": {
                "nombre": "Nombre del remitente",
                "mail": "Correo del remitente"
            },
            "destinatario": {
                "nombre": "Nombre del destinatario",
                "mail": "Correo del destinatario"
            },
            "texto": {
                "asunto": "Este es mi documento con una estructura muy sencilla
                    no contiene atributos ni entidades...",
                "parrafo": "Este es mi documento con una estructura muy sencilla
                    no contiene atributos ni entidades..."
            }
        }
    }
}
```

Es sencillo darse cuenta que debido a esta nueva sintaxis, muy similar a la de un diccionario de Python, la misma información puede almacenarse de forma más ligera.
Comprobémoslo con el ejemplo de más arriba:
"""

import requests

# Obtenemos la información del mensaje en formato XML del repositorio del curso
xml_file = requests.get("https://raw.githubusercontent.com/ITBA-Python/Certificacion-Profesional-Python/main/mensaje.xml")
print(xml_file.text)

# Longitud en bytes del archivo
print(len(xml_file.content))

# Obtenemos la información del mensaje en formato JSON del repositorio del curso
json_file = requests.get("https://raw.githubusercontent.com/ITBA-Python/Certificacion-Profesional-Python/main/mensaje.json")
print(json_file.text)

# Longitud en bytes del archivo
print(len(json_file.content))

"""El módulo requests de Python nos facilita el parseo de los responses del server en los casos que la respuesta está en formato JSON. Ya no necesitamos utilizar el módulo de xml para transformar los datos en un diccionario de Python, sino que la conversión se hace directamente y el código es mucho más sencillo."""

# Parseamos directamente la respuesta del servidor en formato JSON a un diccionario de Python
json_obj = json_file.json()
print(json_obj)

# Podemos trabajar con este diccionario igual que en clases anteriores
mensaje = json_obj["edit_mensaje"]["mensaje"]
rem = mensaje["remitente"]
print(f"Remitente: {rem['nombre']} - {rem['mail']}")

des = mensaje["destinatario"]
print(f"Destinatario: {des['nombre']} - {des['mail']}")

data = mensaje["texto"]
print(f"Asunto: {data['asunto']}\nParrafo: {data['parrafo']}")

"""Además de trabajar con los responses del módulo requests, podemos trabajar con el formato JSON en Python de forma independiente con el módulo json.

### Serialización

Cuando hablamos de formatos de texto, la serialización es el proceso de convertir un objeto en su representación en string. Esto suele hacerse ya que el intercambio de información, ya sea en la web o mediante un cable, se hace de forma serializada en strings o bytes. Con el formato JSON pasa exactamente lo mismo. En el código de Python un JSON representa un diccionario, pero para transmitirlo es necesario convertirlo en string.

El módulo json nos permite hacer esta tarea muy facilmente.
"""

import json

# Ejemplo de objeto diccionario
diccionario = {
    "paises": [
        {"nombre": "Argentina", "codigo": "AR"}, {"nombre": "Brasil", "codigo": "BR"}
    ]
}
print(diccionario)

# Serializamos el objeto
serializado = json.dumps(diccionario)
print(serializado)

"""### Deserealización

La deserealización es el proceso inverso a la serialización. Cuando recibimos un JSON en forma de string debemos deserealizarlo para poder trabajar en nuestro código.
"""

# Ejemplo de JSON serializado
serial = '{"paises": [{"nombre": "Argentina"},{"nombre": "Brasil"}]}'

# Deserealizamos el string
deserial = json.loads(serial)
print(deserial)

# Podemos trabajar con ese diccionario igual que antes
paises = deserial['paises']
for p in paises:
    print(p["nombre"])

"""## Ejercicios

### Mini Desafío 1

Ya aprendimos qué es una API REST y cómo trabajar con el formato JSON. Ahora debemos unir ambos conceptos para trabajar con APIs de forma programática en Python.

En el siguiente link hay una lista de APIs públicas de todo tipo de cosas: <a href="https://publicapis.dev/">APIs Públicas</a>

1. Como primer ejercicio vamos a interactuar con una API de perros, que devuelve un JSON con información sobre datos curiosos de perros. <a href="https://kinduff.github.io/dog-api/?ref=publicapis.dev">Documentación</a>
"""

from os import name
# API de perros
# API de perros
import requests
import json

#def next_link(obj):
#    pass

#https://stackoverflow.com/questions/15785719/how-to-print-a-dictionary-line-by-line-in-python
def dumpclean(obj):
    print ("Objeto recibido type is: {}".format(type(obj)))
    print ("Objeto recibido long is: {}".format(len(obj)))
    print ("+")
    if isinstance(obj, dict):
        for k, v in obj.items():
            if hasattr(v, '__iter__'):
                print (k)
                dumpclean(v)
            else:
                print ('%s : %s' % (k, v))
    elif isinstance(obj, list):
        for v in obj:
            if hasattr(v, '__iter__'):
                dumpclean(v)
            else:
                print (v)
    else:
        print (obj)

db_data  = []
db_links = []
#Lista vacia ya que necesito varios GET para tener toda la info
#db_data.extend(NUEVOS DATOS A AGREGAR)

link = "https://dogapi.dog/api/v2/breeds"
#Link inicial  - puede ser configurado por el usuario -- parametria

has_next_data_link=True
##intento de logica para recorrer la recoleccion de informacion

#PRIMER PEDIDO, LUEGO ITERO SOBRE "NEXT"
while(has_next_data_link):
    r = requests.get(link)
    if r:
        print('Success!')
        #Tomo los datos
        datos =r.json()
        #print(json.dumps(datos, indent = 4)) #Imprime objeto JSON claramente para analisis
        db_data.extend(datos["data"])
        #Busco link proximo requests.get(link_next)
        db_links.extend(datos["links"])
        if "next" in datos["links"]:
            link=datos["links"]["next"]
            print(json.dumps(link, indent = 4)) #Imprime objeto JSON claramente para analisis
        else:
            has_next_data_link=False
            print("No hay mas datos")
        #print(json.dumps(link, indent = 4)) #Imprime objeto JSON claramente para analisis
    else:
        print('An error has occurred.')
#print(json.dumps(links, indent = 4)) #Imprime objeto JSON claramente para analisis
#Segundo pedido    link_next = links["next"]
#link=links["next"]
#r = requests.get(link)
#if r:
#    print('Success!')
#else:
#    print('An error has occurred.')
#datos =r.json()
#db_data.extend(datos["data"])
#links=datos["links"]
#print(json.dumps(links, indent = 4)) #Imprime objeto JSON claramente para analisis
#print(json.dumps(links["next"], indent = 4)) #Imprime objeto JSON claramente para analisis

#has_next_data_link = links["has_next"]
#print("Has next data: {}".format(has_next_data_link))
#r = requests.get(link_next)
#datos =r.json()
#db_data.extend(datos["data"])

#r = requests.get(link_last)
#datos =r.json()
#db_data.extend(datos["data"])
#Debug info
print(type(db_data))
print(len(db_data))
for x in db_data:
   print(x['attributes']["name"])

#ver proxima fuente de datos, si no es la ultima
#links = datos["links"]
#dumpclean(links)

"""2. Ahora vamos a interactuar con una API que tiene datos significativos y que podemos utilizar para hacer algún tipo de procesamiento. Usaremos una API que nos permite obtener las cotizaciones de varios tipos de dólar en pesos argentinos."""

# API de cotizaciones

"""### Mini Desafío 2

Escribir un programa que utilizando la librería json permita que el usuario ingrese un diccionario siguiendo el formato JSON. Y luego imprima todas las llaves con sus valores siguiendo el formato:
```
LLAVE -> VALOR
```

Ejemplo:
```
>>> {"llave1": 12, "llave2": "Hola", 12:13}
"llave1" -> 12
"llave2" -> "Hola"
12 -> 13
```
"""



"""### Mini Desafío 3

Escribir un programa que permita guardar un diccionario en un archivo en formato JSON.
"""



"""### Mini desafío 4

Escribir un programa que permita leer un diccionario a partir de un archivo en formato json.
"""



"""### Mini Desafío 5

Escribir un programa que te pida ingresar:
 -   Moneda de origen
 -   Moneda de destino
 -   Monto de moneda de origen

Y devuelva el monto en la moneda de destino convertido con el tipo del cambio del día. El formato de salida debe ser:
```
MONTO (MONEDA DE ORIGEN) <-> MONTO CONVERITDO (MONEDA DE DESTINO)
```

Ejemplos (puede variar según el dia):
```
>>> EUR
>>> USD
>>> 100
100 (EUR) <-> 100.3 (USD)
```
```
>>> EUR
>>> ARS
>>> 100
100 (EUR) <-> 12796.56 (ARS)
```

**TIP:** Investigar esta [API](https://rates.hirak.site/?ref=publicapis.dev).

**TIP 2:** Los códigos de las monedas los pueden encontrar en este [link](https://es.wikipedia.org/wiki/ISO_4217).
"""



"""# Programacion orientada a objetos

La programación orientada a objetos (POO) es un nuevo paradigma de programación que cambia la forma en que desarrollamos nuestro código. Se basa en el concepto de "objetos", que son una representación de un objeto literal del mundo real. Por ejemplo, podemos representar como un objeto un perro, un auto, una persona, etc.

Esta idea nos permite modelar un problema real identificando los objetos que están involucrados y así organizar mejor el código separando las funcionalidades y estados de cada objeto en bloques independientes de código. Esto facilita enormemente el diseño del programa, la implementación del código y lograr una mayor modularidad.

## Objetos

Los objetos son una representación de objetos del mundo real. Podemos pensarlos como estructuras que encapsulan el estado del objeto y sus funcionalidades básicas. En progamación se suelen denominar atributos y métodos a las variables y funciones que se definen como parte de un objeto.

Por ejemplo, si queremos representar un perro como un objeto, podemos definir los atributos nombre, raza, edad; y los métodos ladrar, caminar, alimentar, nombrar.

## Conceptos básicos

La POO se basa en diferentes conceptos fundamentales, entre ellos cuatro que son muy importantes para entender las diferencias con el paradigma de programación que venimos usando (programación estructurada):

- **Abstracción:** los objetos nos permiten abstraernos de los detalles de implementación de las funcionalidades de ese objeto. Por ejemplo, si tenemos el objeto perro con un método caminar, no nos importa cómo está definida la función para hacer caminar a un perro, simplemente la usamos abstrayéndonos de todo el código que está detrás.

- **Encapsulamiento:** de forma similar a la abstracción, el concepto de encapsulamiento se refiere a reunir todas las variables y funcionalidades de una misma entidad como parte del objeto. La diferencia con la abstracción es que el encapsulamiento apunta a la idea de que desde el lado del desarrollador del código del objeto, al estar los métodos y atributos encapsulados podemos iterar y cambiar la forma en que implementamos esas funciones, sin que el usuario del objeto note alguna diferencia en el funcionamiento.

- **Herencia:** los objetos en general no están aisalados, sino que tienen relaciones entre sí. Este es un concepto clave de la POO que permite definir en el código estas relaciones entre clases, como por ejemplo Animal y Perro (tienen una relación jerárquica en el sentido que un perro es también un animal, Animal -> Perro).

- **Polimorfismo:** este concepto se refiere a que en difentes objetos podemos tener el mismo método (con el mismo nombre), pero que se comporte de forma diferente según a que objeto esté asociado y que el usuario de los objetos pueda usarlos de forma indistinta. Por ejemplo los objetos de tipo perro y auto puede tener el mismo método mover(), que ejecutará funciones totalmente distintas dependiende si se está llamanda desde el objeto auto o el objeto perro.

Todos estos conceptos son generales de la POO y se aplican en cualquier lenguaje de programación.

## Clases y objetos

En Python podemos adoptar este paradigma de programación utilizando clases. Las clases son la forma que tiene Python de modelar objetos.
Llevemos a código los ejemplos de objetos que venimos mencionando.
"""

# Clase que reprensta al objeto Perro
class Perro:

    # Atributos
    nombre = ""
    edad = 0
    raza = ""

    # Inicializador
    def __init__(self, nombre, edad, raza):
        self.nombre = nombre
        self.edad = edad
        self.raza = raza

    # Métodos
    def ladrar(self):
        print("GUAU GUAU")

    def crecer(self):
        self.edad += 1

    def nombrar(self, nombre):
        self.nombre = nombre

"""Notemos varias cosas de este ejemplo.

- En general, las clases suelen nombrase con una mayúscula al principio (es Perro y no perro).

- La clase tiene una función especial \_\_init\_\_() que se utiliza para inicilizar el objeto.

- Todos los métodos de instancia reciben siempre un parámetros self.

Si bien venimos hablando todo el tiempo de objetos, en Python un objeto tiene una definición específica. Lo que definimos anteriormente es una <b>CLASE</b>. Puede pensarse como un template de como debe estar estructurado un Perro, que variables contiene y que funciones puedo ejecutar sobre ese Perro.

En cambio, un <b>OBJETO</b> es una instancia de una clase. Se refiere a la variable particular que usamos en el código. Se dice que cuando creamos un objeto, estamos instanciando la clase. En el ejemplo del perro, la clase representa a todos los objetos de tipo Perro, y establece que todos los perros tendrán un nombre, una edad y una raza. El objeto en cambio es la instancia en particular de Perro, representa al perro llamado Pelusa, de 5 años y de la raza Caniche.

Veamos ejemplos de código.
"""

# Definimos una variable de tipo Perro, una instancia
miPerro = Perro("Pelusa", 5, "caniche")

# Podemos obtener los atributos del objeto usando la notación punto
print(f"Mi perro tiene {miPerro.edad} años.")
print(f"Mi perro se llama {miPerro.nombre}")

# También podemos usar los métodos de la instancia con la misma notación
# Modificamos el nombre de mi perro
miPerro.nombrar("Juan")
print(f"Mi perro se llama {miPerro.nombre}")

# Hacemos crecer a mi perro
miPerro.crecer()
print(f"Mi perro tiene {miPerro.edad} años.")

"""### self

Mencionamos en la definición de la clase que todos los métodos reciben el parámetro self, pero cuando llamamos al método nombrar() en el código anterior solamente le pasamos un argumento, el nuevo nombre.

Esta es la forma que tiene Python de que al trabajar con objetos, estamos interactuando con las variables y métodos de esa instancia en particular de la clase. Python se encarga automáticamente de agregar como primer parámetros en la llamada a la función una referencia al mismo objeto, de ahí el nombre self.

Se puede pensar self como una referencia a mí mismo. Cuando usamos self en la definición de la clase, por ejemplo en el método
```python
def crecer(self):
        self.edad += 1
```

estamos modificando el atributo edad de la instancia específica de Perro desde la que se está llamando al método, en este caso del objeto miPerro.

## Ejercicios

### Mini Desafío 6

Escribir una clase `Cuadrado` que reciba el largo del lado y permita obtener el perimetro, el area y permita dibujar el cuadrado en consola.

Ejemplos:
```python
>>> miCuadrado = Cuadrado(1)
>>> print(miCuadrado.area)
1
>>> print(miCuadrado.perimetro)
4
>>> miCuadrado.imprimir()
┌───┐
│   │
└───┘
```
```python
>>> miCuadrado = Cuadrado(3)
>>> print(miCuadrado.area)
9
>>> print(miCuadrado.perimetro)
12
>>> miCuadrado.imprimir()
┌─────────┐
│         │
│         │
│         │
└─────────┘
```
**TIP:** Copiar los caracteres de los ejemplos.
"""



"""### Mini Desafío 7

Crear una clase `Alumno` debe recibir los siguientes parámetros de constructor:


*   Nombre
*   Apellido
*   Legajo (Número único que identifica al alumno)

La clase tambien debe incluir los siguientes métodos:


*   .agregar_nota(nota, peso) - Recibe una nota y el peso de la materia.
*   .obtener_promedio_academico() - Promedio ponderado con el peso de cada materia.
*   .obtener_promedio_lineal() - Promedio sin ponderar el peso.

Ejemplos:
```python
>>> alumno1 = Alumno('Juana', 'Sanchez', 12345)
>>> alumno2 = Alumno('Juan', 'Perez', 12346)
>>> # Si no tienen notas debe decir SIN NOTAS
>>> alumno1.obtener_promedio_academico()
SIN NOTAS
>>> # Agregamos una nota a cada uno
>>> alumno1.agregar_nota(10, 6)
>>> alumno2.agregar_nota(8, 6)
>>> # Verificamos que los dos promedios son iguales
>>> alumno1.obtener_promedio_academico()
Juana Sanchez - Académico - 10
>>> alumno2.obtener_promedio_academico()
Juan Perez - Académico - 8
>>> alumno1.obtener_promedio_lineal()
Juana Sanchez - Lineal - 10
>>> alumno2.obtener_promedio_lineal()
Juan Perez - Lineal - 8
>>> # Agregamos una segunda nota
>>> alumno1.agregar_nota(9, 3)
>>> alumno2.agregar_nota(10, 3)
>>> # Verficamos los promedios
>>> alumno1.obtener_promedio_academico()
Juana Sanchez - Académico - 9.6666
>>> alumno2.obtener_promedio_academico()
Juan Perez - Académico - 8.6666
>>> alumno1.obtener_promedio_lineal()
Juana Sanchez - Lineal - 9.5
>>> alumno2.obtener_promedio_lineal()
Juan Perez - Lineal - 9
```
"""



"""# Ejercicios Integradores

## Ejercicio 1

Re-escribir el Mini Desafío 5 como una clase que permita mantener el valor de cambio actualizado.

La clase la llamaremos `FXConversion` y debe guardar el último tipo de cambio por 30 segundos antes de actualizarlo.

Los parametros de inicialización:


*   Moneda de origen
*   Moneda de destino

Métodos:


*   .conversion_rate() - Imprime el tipo de cambio.
*   .conversion(monto) - Debe convertir el monto de la moneda de origen a la de destino.
*   .conversion(monto, reverse=True) - Debe convertir el monto de la moneda de destino a la de origen

**TIP**: Poner un print cuando hacen los llamados a la API para saber si estan llamando solo cuando es necesario.

**TIP 2**: Pueden importar `from time import sleep` y con la funcion `sleep(segundos)` pueden dormir el programa por los segundos que quieran.

Ejemplo:
```python
>>> gbp2usd = FXConversion("GBP", "USD")
>>> gbp2usd.conversion_rate()
Actualizando el valor de cambio.
1 GBP = 1.19 USD
>>> gbp2usd.conversion_rate()
1 GBP = 1.19 USD
>>> gbp2usd.conversion(10)
10 GBP = 11.9 USD
>>> gbp2usd.conversion(10, reverse=True)
10 USD = 8.40 USD
>>> sleep(30)
>>> gbp2usd.conversion(10)
Actualizando el valor de cambio.
10 GBP = 11.8 USD
```
"""



"""## Ejercicio 2

Escribir una clase que permita interactuar y mantener un diccionario guardado en un archivo. Todos los cambios deben ser guardados al archivo.

La clase debe llamarse `MyDictDB`.

Parámetros de inicialización:

*   Nombre del archivo - Si existe debe cargar el diccionario, si no existe debe crearlo con un diccionario vacio.

Métodos:


*   .update_key(key, value) - Actualiza o crea una key dentro del diccionario.
*   .delete_key(key) - Elimina una key
"""



"""## Ejercicio 3

Escribir una clase `News` que obtenga los datos de un feed rss visto la clase pasada y guarde las noticias en formato json.

La clase debe cumplir lo siguiente:


*   Debe detectar noticias duplicadas y unicamente guardar una.
*   Cuando se inicializa debe cargar las noticias que ya tiene cargadas.
*   Debe calcular las siguientes métricas:
    *    Cantidad total de noticias.
    *    Cantidad total de noticias por día.
    *    Dada una palabra dar la cantidad de noticias que poseen esa palabra. Ejemplo: Cuantas noticias contienen la palabra "Messi".
*   Debe poseer un método para actualizar y traer las nuevas noticias.
*   Debe poseer un método para imprimir todas las noticias.
*   Debe poseer un método para imprimir las últimas X noticias.
"""

